# -*- coding: utf-8 -*-

################################################################################
## Form generated from reading UI file 'design.ui'
##
## Created by: Qt User Interface Compiler version 5.15.2
##
## WARNING! All changes made in this file will be lost when recompiling UI file!
################################################################################

from PySide2.QtCore import *
from PySide2.QtGui import *
from PySide2.QtWidgets import *

from smart_graphics import SmartGraphicsView


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        if not MainWindow.objectName():
            MainWindow.setObjectName(u"MainWindow")
        MainWindow.resize(1440, 805)
        sizePolicy = QSizePolicy(QSizePolicy.Expanding, QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        self.actionOpen = QAction(MainWindow)
        self.actionOpen.setObjectName(u"actionOpen")
        self.actionPalette = QAction(MainWindow)
        self.actionPalette.setObjectName(u"actionPalette")
        self.actionViridis = QAction(MainWindow)
        self.actionViridis.setObjectName(u"actionViridis")
        self.actionPlasma = QAction(MainWindow)
        self.actionPlasma.setObjectName(u"actionPlasma")
        self.actionInferno = QAction(MainWindow)
        self.actionInferno.setObjectName(u"actionInferno")
        self.actionMagma = QAction(MainWindow)
        self.actionMagma.setObjectName(u"actionMagma")
        self.actionCividis = QAction(MainWindow)
        self.actionCividis.setObjectName(u"actionCividis")
        self.actionJet = QAction(MainWindow)
        self.actionJet.setObjectName(u"actionJet")
        self.actionGray = QAction(MainWindow)
        self.actionGray.setObjectName(u"actionGray")
        self.actionNo_palette = QAction(MainWindow)
        self.actionNo_palette.setObjectName(u"actionNo_palette")
        self.actionOpen_Folder = QAction(MainWindow)
        self.actionOpen_Folder.setObjectName(u"actionOpen_Folder")
        self.actionNext_File = QAction(MainWindow)
        self.actionNext_File.setObjectName(u"actionNext_File")
        self.actionPrevious_File = QAction(MainWindow)
        self.actionPrevious_File.setObjectName(u"actionPrevious_File")
        self.actionShow_File_Tree = QAction(MainWindow)
        self.actionShow_File_Tree.setObjectName(u"actionShow_File_Tree")
        self.actionShow_File_Tree.setCheckable(True)
        self.centralWidget = QWidget(MainWindow)
        self.centralWidget.setObjectName(u"centralWidget")
        self.histogramWidget_MIP = QWidget(self.centralWidget)
        self.histogramWidget_MIP.setObjectName(u"histogramWidget_MIP")
        self.histogramWidget_MIP.setGeometry(QRect(29, 509, 250, 250))
        sizePolicy1 = QSizePolicy(QSizePolicy.Fixed, QSizePolicy.Fixed)
        sizePolicy1.setHorizontalStretch(0)
        sizePolicy1.setVerticalStretch(0)
        sizePolicy1.setHeightForWidth(self.histogramWidget_MIP.sizePolicy().hasHeightForWidth())
        self.histogramWidget_MIP.setSizePolicy(sizePolicy1)
        self.histogramWidget_MIP.setMinimumSize(QSize(250, 250))
        self.histogramWidget_MIP.setMaximumSize(QSize(250, 250))
        self.tableMetrics = QTableWidget(self.centralWidget)
        if (self.tableMetrics.columnCount() < 5):
            self.tableMetrics.setColumnCount(5)
        if (self.tableMetrics.rowCount() < 7):
            self.tableMetrics.setRowCount(7)
        __qtablewidgetitem = QTableWidgetItem()
        __qtablewidgetitem.setTextAlignment(Qt.AlignCenter);
        self.tableMetrics.setItem(0, 0, __qtablewidgetitem)
        self.tableMetrics.setObjectName(u"tableMetrics")
        self.tableMetrics.setGeometry(QRect(1000, 510, 360, 232))
        sizePolicy1.setHeightForWidth(self.tableMetrics.sizePolicy().hasHeightForWidth())
        self.tableMetrics.setSizePolicy(sizePolicy1)
        self.tableMetrics.setMaximumSize(QSize(360, 232))
        self.tableMetrics.setVerticalScrollBarPolicy(Qt.ScrollBarAlwaysOff)
        self.tableMetrics.setHorizontalScrollBarPolicy(Qt.ScrollBarAlwaysOff)
        self.tableMetrics.setAutoScroll(False)
        self.tableMetrics.setEditTriggers(QAbstractItemView.NoEditTriggers)
        self.tableMetrics.setTabKeyNavigation(True)
        self.tableMetrics.setProperty("showDropIndicator", True)
        self.tableMetrics.setAlternatingRowColors(False)
        self.tableMetrics.setShowGrid(True)
        self.tableMetrics.setCornerButtonEnabled(True)
        self.tableMetrics.setRowCount(7)
        self.tableMetrics.setColumnCount(5)
        self.tableMetrics.horizontalHeader().setVisible(True)
        self.tableMetrics.horizontalHeader().setCascadingSectionResizes(True)
        self.tableMetrics.horizontalHeader().setMinimumSectionSize(72)
        self.tableMetrics.horizontalHeader().setDefaultSectionSize(72)
        self.tableMetrics.horizontalHeader().setHighlightSections(True)
        self.tableMetrics.horizontalHeader().setStretchLastSection(False)
        self.tableMetrics.verticalHeader().setVisible(False)
        self.tableMetrics.verticalHeader().setMinimumSectionSize(30)
        self.tableMetrics.verticalHeader().setDefaultSectionSize(30)
        self.sliderWidget = QWidget(self.centralWidget)
        self.sliderWidget.setObjectName(u"sliderWidget")
        self.sliderWidget.setGeometry(QRect(300, 470, 810, 40))
        sizePolicy1.setHeightForWidth(self.sliderWidget.sizePolicy().hasHeightForWidth())
        self.sliderWidget.setSizePolicy(sizePolicy1)
        self.sliderWidget.setMinimumSize(QSize(810, 40))
        self.sliderWidget.setMaximumSize(QSize(810, 40))
        self.sliderZ = QSlider(self.sliderWidget)
        self.sliderZ.setObjectName(u"sliderZ")
        self.sliderZ.setGeometry(QRect(205, 0, 400, 40))
        sizePolicy1.setHeightForWidth(self.sliderZ.sizePolicy().hasHeightForWidth())
        self.sliderZ.setSizePolicy(sizePolicy1)
        self.sliderZ.setOrientation(Qt.Horizontal)
        self.current_z_label = QLabel(self.sliderWidget)
        self.current_z_label.setObjectName(u"current_z_label")
        self.current_z_label.setGeometry(QRect(630, 10, 60, 21))
        sizePolicy2 = QSizePolicy(QSizePolicy.Fixed, QSizePolicy.Minimum)
        sizePolicy2.setHorizontalStretch(0)
        sizePolicy2.setVerticalStretch(0)
        sizePolicy2.setHeightForWidth(self.current_z_label.sizePolicy().hasHeightForWidth())
        self.current_z_label.setSizePolicy(sizePolicy2)
        self.current_z_label.setTextFormat(Qt.PlainText)
        self.pushButtonCenterCircles = QPushButton(self.sliderWidget)
        self.pushButtonCenterCircles.setObjectName(u"pushButtonCenterCircles")
        self.pushButtonCenterCircles.setGeometry(QRect(30, 5, 113, 32))
        self.graphicsView = SmartGraphicsView(self.centralWidget)
        self.graphicsView.setObjectName(u"graphicsView")
        self.graphicsView.setGeometry(QRect(300, 63, 400, 400))
        sizePolicy1.setHeightForWidth(self.graphicsView.sizePolicy().hasHeightForWidth())
        self.graphicsView.setSizePolicy(sizePolicy1)
        self.graphicsView.setMinimumSize(QSize(400, 200))
        self.graphicsView.setMaximumSize(QSize(400, 400))
        self.graphicsView.setSizeIncrement(QSize(0, 0))
        self.graphicsView.setAutoFillBackground(False)
        self.graphicsView_MIP = SmartGraphicsView(self.centralWidget)
        self.graphicsView_MIP.setObjectName(u"graphicsView_MIP")
        self.graphicsView_MIP.setGeometry(QRect(710, 63, 400, 400))
        sizePolicy1.setHeightForWidth(self.graphicsView_MIP.sizePolicy().hasHeightForWidth())
        self.graphicsView_MIP.setSizePolicy(sizePolicy1)
        self.graphicsView_MIP.setMinimumSize(QSize(400, 200))
        self.graphicsView_MIP.setMaximumSize(QSize(400, 400))
        self.graphicsView_MIP.setSizeIncrement(QSize(0, 0))
        self.graphicsView_MIP.setBaseSize(QSize(400, 400))
        self.graphicsView_MIP.setAutoFillBackground(False)
        self.sliderMIP = QSlider(self.centralWidget)
        self.sliderMIP.setObjectName(u"sliderMIP")
        self.sliderMIP.setGeometry(QRect(1120, 60, 40, 400))
        sizePolicy1.setHeightForWidth(self.sliderMIP.sizePolicy().hasHeightForWidth())
        self.sliderMIP.setSizePolicy(sizePolicy1)
        self.sliderMIP.setOrientation(Qt.Vertical)
        self.MIP_layers_label = QLabel(self.centralWidget)
        self.MIP_layers_label.setObjectName(u"MIP_layers_label")
        self.MIP_layers_label.setGeometry(QRect(1120, 480, 61, 21))
        sizePolicy3 = QSizePolicy(QSizePolicy.Minimum, QSizePolicy.Minimum)
        sizePolicy3.setHorizontalStretch(0)
        sizePolicy3.setVerticalStretch(0)
        sizePolicy3.setHeightForWidth(self.MIP_layers_label.sizePolicy().hasHeightForWidth())
        self.MIP_layers_label.setSizePolicy(sizePolicy3)
        self.MIP_layers_label.setTextFormat(Qt.PlainText)
        self.pathLabel = QLabel(self.centralWidget)
        self.pathLabel.setObjectName(u"pathLabel")
        self.pathLabel.setGeometry(QRect(390, 30, 631, 16))
        sizePolicy1.setHeightForWidth(self.pathLabel.sizePolicy().hasHeightForWidth())
        self.pathLabel.setSizePolicy(sizePolicy1)
        self.pathLabel.setAlignment(Qt.AlignCenter)
        self.groupBox_Epres_MIP = QGroupBox(self.centralWidget)
        self.groupBox_Epres_MIP.setObjectName(u"groupBox_Epres_MIP")
        self.groupBox_Epres_MIP.setGeometry(QRect(340, 530, 120, 80))
        font = QFont()
        font.setPointSize(20)
        self.groupBox_Epres_MIP.setFont(font)
        self.groupBox_Epres_MIP.setAlignment(Qt.AlignCenter)
        self.labelEpresMIP = QLabel(self.groupBox_Epres_MIP)
        self.labelEpresMIP.setObjectName(u"labelEpresMIP")
        self.labelEpresMIP.setGeometry(QRect(20, 30, 80, 40))
        sizePolicy1.setHeightForWidth(self.labelEpresMIP.sizePolicy().hasHeightForWidth())
        self.labelEpresMIP.setSizePolicy(sizePolicy1)
        self.labelEpresMIP.setMinimumSize(QSize(80, 40))
        self.labelEpresMIP.setMaximumSize(QSize(80, 40))
        font1 = QFont()
        font1.setPointSize(18)
        self.labelEpresMIP.setFont(font1)
        self.labelEpresMIP.setAlignment(Qt.AlignCenter)
        self.groupBox_Econd_MIP = QGroupBox(self.centralWidget)
        self.groupBox_Econd_MIP.setObjectName(u"groupBox_Econd_MIP")
        self.groupBox_Econd_MIP.setGeometry(QRect(340, 640, 120, 80))
        self.groupBox_Econd_MIP.setFont(font)
        self.groupBox_Econd_MIP.setAlignment(Qt.AlignCenter)
        self.labelEcondMIP = QLabel(self.groupBox_Econd_MIP)
        self.labelEcondMIP.setObjectName(u"labelEcondMIP")
        self.labelEcondMIP.setGeometry(QRect(20, 30, 80, 40))
        sizePolicy1.setHeightForWidth(self.labelEcondMIP.sizePolicy().hasHeightForWidth())
        self.labelEcondMIP.setSizePolicy(sizePolicy1)
        self.labelEcondMIP.setMinimumSize(QSize(80, 40))
        self.labelEcondMIP.setMaximumSize(QSize(80, 40))
        self.labelEcondMIP.setFont(font1)
        self.labelEcondMIP.setAlignment(Qt.AlignCenter)
        self.histogramWidget_Volume = QWidget(self.centralWidget)
        self.histogramWidget_Volume.setObjectName(u"histogramWidget_Volume")
        self.histogramWidget_Volume.setGeometry(QRect(500, 509, 250, 250))
        sizePolicy1.setHeightForWidth(self.histogramWidget_Volume.sizePolicy().hasHeightForWidth())
        self.histogramWidget_Volume.setSizePolicy(sizePolicy1)
        self.histogramWidget_Volume.setMinimumSize(QSize(250, 250))
        self.histogramWidget_Volume.setMaximumSize(QSize(250, 250))
        self.groupBox_Econd_Volume = QGroupBox(self.centralWidget)
        self.groupBox_Econd_Volume.setObjectName(u"groupBox_Econd_Volume")
        self.groupBox_Econd_Volume.setGeometry(QRect(810, 640, 120, 80))
        self.groupBox_Econd_Volume.setFont(font)
        self.groupBox_Econd_Volume.setAlignment(Qt.AlignCenter)
        self.labelEcondVolume = QLabel(self.groupBox_Econd_Volume)
        self.labelEcondVolume.setObjectName(u"labelEcondVolume")
        self.labelEcondVolume.setGeometry(QRect(20, 30, 80, 40))
        sizePolicy1.setHeightForWidth(self.labelEcondVolume.sizePolicy().hasHeightForWidth())
        self.labelEcondVolume.setSizePolicy(sizePolicy1)
        self.labelEcondVolume.setMinimumSize(QSize(80, 40))
        self.labelEcondVolume.setMaximumSize(QSize(80, 40))
        self.labelEcondVolume.setFont(font1)
        self.labelEcondVolume.setAlignment(Qt.AlignCenter)
        self.groupBox_Epres_Volume = QGroupBox(self.centralWidget)
        self.groupBox_Epres_Volume.setObjectName(u"groupBox_Epres_Volume")
        self.groupBox_Epres_Volume.setGeometry(QRect(810, 530, 120, 80))
        self.groupBox_Epres_Volume.setFont(font)
        self.groupBox_Epres_Volume.setAlignment(Qt.AlignCenter)
        self.labelEpresVolume = QLabel(self.groupBox_Epres_Volume)
        self.labelEpresVolume.setObjectName(u"labelEpresVolume")
        self.labelEpresVolume.setGeometry(QRect(20, 30, 80, 40))
        sizePolicy1.setHeightForWidth(self.labelEpresVolume.sizePolicy().hasHeightForWidth())
        self.labelEpresVolume.setSizePolicy(sizePolicy1)
        self.labelEpresVolume.setMinimumSize(QSize(80, 40))
        self.labelEpresVolume.setMaximumSize(QSize(80, 40))
        self.labelEpresVolume.setFont(font1)
        self.labelEpresVolume.setAlignment(Qt.AlignCenter)
        MainWindow.setCentralWidget(self.centralWidget)
        self.menuBar = QMenuBar(MainWindow)
        self.menuBar.setObjectName(u"menuBar")
        self.menuBar.setGeometry(QRect(0, 0, 1440, 24))
        self.menu = QMenu(self.menuBar)
        self.menu.setObjectName(u"menu")
        self.menuPalette = QMenu(self.menuBar)
        self.menuPalette.setObjectName(u"menuPalette")
        self.menuView = QMenu(self.menuBar)
        self.menuView.setObjectName(u"menuView")
        MainWindow.setMenuBar(self.menuBar)

        self.menuBar.addAction(self.menu.menuAction())
        self.menuBar.addAction(self.menuPalette.menuAction())
        self.menuBar.addAction(self.menuView.menuAction())
        self.menu.addAction(self.actionOpen)
        self.menu.addAction(self.actionOpen_Folder)
        self.menu.addAction(self.actionPrevious_File)
        self.menu.addAction(self.actionNext_File)
        self.menuPalette.addAction(self.actionGray)
        self.menuPalette.addAction(self.actionViridis)
        self.menuPalette.addAction(self.actionPlasma)
        self.menuPalette.addAction(self.actionInferno)
        self.menuPalette.addAction(self.actionMagma)
        self.menuPalette.addAction(self.actionCividis)
        self.menuPalette.addAction(self.actionJet)
        self.menuView.addAction(self.actionShow_File_Tree)

        self.retranslateUi(MainWindow)

        QMetaObject.connectSlotsByName(MainWindow)
    # setupUi

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(QCoreApplication.translate("MainWindow", u"oct viewer", None))
        self.actionOpen.setText(QCoreApplication.translate("MainWindow", u"Open", None))
        self.actionPalette.setText(QCoreApplication.translate("MainWindow", u"Color palette", None))
        self.actionViridis.setText(QCoreApplication.translate("MainWindow", u"Viridis", None))
        self.actionPlasma.setText(QCoreApplication.translate("MainWindow", u"Plasma", None))
        self.actionInferno.setText(QCoreApplication.translate("MainWindow", u"Inferno", None))
        self.actionMagma.setText(QCoreApplication.translate("MainWindow", u"Magma", None))
        self.actionCividis.setText(QCoreApplication.translate("MainWindow", u"Cividis", None))
        self.actionJet.setText(QCoreApplication.translate("MainWindow", u"Jet", None))
        self.actionGray.setText(QCoreApplication.translate("MainWindow", u"Gray", None))
        self.actionNo_palette.setText(QCoreApplication.translate("MainWindow", u"No palette", None))
        self.actionOpen_Folder.setText(QCoreApplication.translate("MainWindow", u"Open Folder", None))
        self.actionNext_File.setText(QCoreApplication.translate("MainWindow", u"Next File", None))
        self.actionPrevious_File.setText(QCoreApplication.translate("MainWindow", u"Previous File", None))
        self.actionShow_File_Tree.setText(QCoreApplication.translate("MainWindow", u"Show File Tree", None))

        __sortingEnabled = self.tableMetrics.isSortingEnabled()
        self.tableMetrics.setSortingEnabled(False)
        self.tableMetrics.setSortingEnabled(__sortingEnabled)

        self.current_z_label.setText("")
        self.pushButtonCenterCircles.setText(QCoreApplication.translate("MainWindow", u"Center Circles", None))
#if QT_CONFIG(shortcut)
        self.pushButtonCenterCircles.setShortcut(QCoreApplication.translate("MainWindow", u"C", None))
#endif // QT_CONFIG(shortcut)
        self.MIP_layers_label.setText("")
        self.pathLabel.setText("")
        self.groupBox_Epres_MIP.setTitle(QCoreApplication.translate("MainWindow", u"Epres", None))
        self.labelEpresMIP.setText("")
        self.groupBox_Econd_MIP.setTitle(QCoreApplication.translate("MainWindow", u"Econd", None))
        self.labelEcondMIP.setText("")
        self.groupBox_Econd_Volume.setTitle(QCoreApplication.translate("MainWindow", u"Econd", None))
        self.labelEcondVolume.setText("")
        self.groupBox_Epres_Volume.setTitle(QCoreApplication.translate("MainWindow", u"Epres", None))
        self.labelEpresVolume.setText("")
        self.menu.setTitle(QCoreApplication.translate("MainWindow", u"File", None))
        self.menuPalette.setTitle(QCoreApplication.translate("MainWindow", u"Palette", None))
        self.menuView.setTitle(QCoreApplication.translate("MainWindow", u"View", None))
    # retranslateUi

