# Включить автоисправление
fix = true

# Длина строки
line-length = 100

# Исключаем тесты из проверок
exclude = ["tests"]

[lint]
# Выбрать правила - не слишком строгие, но полезные
select = [
    "E", # стандартные ошибки синтаксиса
    "F", # pyflakes (неиспользуемые импорты и т.д.)
    "I", # isort (сортировка импортов)
    "UP", # улучшения синтаксиса под новые версии Python
    "B", # обнаружение потенциальных багов
    # "PERF", # performance — подсказки по улучшению производительности
]
# Игнорировать некоторые слишком строгие правила
ignore = [
    "E501", # длина строки
]
# Исключить ненужные директории
exclude = [".git", "__pycache__", "venv", ".venv", "tests"]

# Настройки форматирования
[format]
quote-style = "single"
indent-style = "space"
line-ending = "auto"
exclude = ["tests"]
skip-magic-trailing-comma = false # Всегда добавлять висящую запятую
docstring-code-format = true # Приводить код внутри docstring к единому стилю
